src/components/LeftSidebar.tsx
src/constants/index.ts

- 홈화면 아이콘 수정(Outline 아이콘으로 변경)
- 사이드바 label 마진 변경
- 로그아웃 버튼 마진 변경, 배경색 없앰

Bottom side bar

---

src/app/[id]/map/page.tsx
src/app/[id]/page.tsx
src/app/layout.tsx
src/components/Mypage/index.tsx
src/styles/globals.css

마이페이지는 랜딩페이지만 UI 우선적으로 구현하고, 나의 맛집지도는 api 연결하면서 구현 예정.
전체적은 스타일은 api 연결 후 수정 계획입니다. 
- 반응형 디자인 구현

Feat: 마이페이지-랜딩페이지 UI 구현

---

src/components/Feed.tsx
src/components/Topbar.tsx

- home 페이지에서 상단바의 경우, 스크롤을 내리면, 상단바가 사라지고, 스크롤을 올리면 상단바가 보이도록 구현
- 게시글 좌우 패딩 적용

Feat : home 페이지 스크롤에 따른 상단바 표시 변경, Feed 좌우 패딩 적용

---

src/components/Auth/LoginForm.tsx
src/store/useUserStore.ts
src/types/apiTypes.ts

- loginForm 에 추가사항이 있어서 은상님께서 한 번 확인해주시면 좋을 것 같아요!
- 로그인 성공시 userStore에 로그인 응답값(id, nickName, profileImage, accessToken)을 저장 후, /main/home 으로 페이지 이동 시킵니다.

User store

---

src/app/auth/kakao/callback/page.tsx
src/components/Auth/ChangePassword.tsx
src/components/Auth/LoginForm.tsx
src/components/Auth/PasswordCode.tsx
src/components/Bottombar.tsx
src/components/Mypage/index.tsx
src/services/auth.ts
src/store/useSignUpStore.ts
src/types/apiTypes.ts

스테시 불러오는 과정에서 자동 git add가 돼서 커밋이 한번에 올라간 부분이 있습니다.

Feat: auth 관련 페이지 수정 및 하단 바 마이페이지 url 수정

---

src/components/Auth/LoginForm.tsx
src/services/index.ts
src/services/post.ts

- vercel 빌드에서 에러 났는데, localStorage 접근 관련 이슈라고 하여 그 부분 변경.

Fix : localStorage 직접 접근 금지 후, getstate 통해서 전역변수 사용

---

src/app/main/feed/[id]/page.tsx
src/app/main/layout.tsx
src/app/main/liked/page.tsx
src/app/main/recommend/page.tsx
src/app/test/page.tsx
src/components/Auth/AuthCheck.ts
src/components/Common/Header/index.tsx
src/components/Feed/Feed.tsx
src/components/Feed/FeedModal.tsx
src/components/Feed/Feeds.tsx
src/components/Main/Bottombar.tsx
src/components/Main/Topbar.tsx
src/components/Mypage/MyMap.tsx
src/components/Mypage/MyProfile.tsx
src/components/Restaurant/AreaSelector.tsx
src/components/Restaurant/ShopThumbList.tsx
src/components/SearhUser/SearhUser.tsx

- 상단바, 하단바 고정, 숨김, 보임 등 레이아웃 수정

Fix : 다양한 레이아웃 요소 수정

---

src/components/Feed/Feed.tsx
src/components/Feed/ImageSlide.tsx
src/components/Feed/replyList.tsx

- 클라이언트 베이스 url 변경 : foodielog.shop
- 페이지 이동 경로 수정(댓글목록 -> 해당유저 마이페이지)
- 이미지 슬라이드 터치 부분 기능 오류 수정

Fix : 자잘한 기능 수정

---

src/app/auth/kakao/callback/layout.tsx
src/app/auth/kakao/callback/page.tsx
src/app/auth/kakao/layout.tsx
src/app/auth/kakao/page.tsx
src/components/Auth/SignUpProfile.tsx
src/components/Settings/MySettings.tsx
src/components/Settings/SettingModal.tsx
src/services/index.ts
src/services/kakao.ts
src/store/useUserStore.ts

- 카카오 이메일 인증 페이지 디자인 추후 상의
- 카카오 로그인 refresh 토큰 관련 로직 추가 예정
- 카카오 로그인 테스트 성공
- 카카오 탈퇴 테스트 필요

feat: 카카오 로그인, 로그아웃, 회원탈퇴 구현

---

src/app/main/[id]/page.tsx
src/app/main/mypage/page.tsx
src/components/Auth/AuthCheck.ts
src/components/Auth/SignUpProfile.tsx
src/components/Auth/SignUpTerms.tsx
src/components/Feed/Feed.tsx
src/components/Feed/FeedModal.tsx
src/components/Map/MyListMap.tsx
src/components/Mypage/MyProfile.tsx
src/components/Mypage/MyShopItem.tsx
src/components/Settings/SettingModal.tsx
src/services/auth.ts
src/services/mypage.ts
src/store/useSignUpStore.ts

- 맵 오버레이 ui 추가했으나, 디테일한 디자인 변경이 까다로워서 시간이 걸림
- console.log도 toast로 부분적으로 변경

feat: 맵 오버레이 ui 추가 및 토스트 구현, 프로필 사진 스타일 수정

---

src/app/main/mypage/edit/page.tsx
src/components/Mypage/MyProfile.tsx
src/components/Mypage/MyProfileSettings.tsx

- 프로필 수정 페이지 분리 -> 프로필 수정 후 페이지 전환 이슈 해결

refactor: 프로필 수정 페이지 분리 및 코드 수정

---

src/components/Common/Menu/DropDown.tsx
src/components/Feed/Feed.tsx
src/components/Feed/FeedModal.tsx
src/components/Feed/Feeds.tsx
src/store/useFeedStore.ts

- 피드 수정 이슈 해결
- 수정 후 바로 피드에 수정사항이 반영되는 로직 필요

refactor: 피드 수정 로직 수정

---

src/components/Auth/ChangePassword.tsx
src/components/Auth/PasswordCode.tsx
src/components/Auth/SignUpProfile.tsx
src/components/Mypage/MyProfileSettings.tsx
src/components/PostForm/PostContent.tsx
src/components/PostForm/PostSearch.tsx
src/components/Settings/MySettings.tsx
src/components/Settings/SettingModal.tsx
src/components/Settings/SettingPassword.tsx
src/services/index.ts
src/services/settings.ts
src/styles/globals.css

feat: 회원탈퇴 및 로그아웃 수정

---

src/app/auth/kakao/callback/page.tsx
src/app/main/liked/page.tsx
src/app/main/map/[id]/page.tsx
src/app/main/mypage/map/page.tsx
src/components/Common/Header/index.tsx
src/components/Map/MyMap.tsx
src/components/PostForm/PostImage.tsx
src/types/mypage.ts

- 사진 추가 (이미지 선택) UI 수정
- 헤더 스타일 수정
- my map 타이틀 변경할 수 있도록 헤더 수정 (타 회원 닉네임 논의 필요)
- 로딩 UI 추가

refactor: 이미지 선택, 헤더 스타일 및 my map 컴포넌트 헤더 타이틀 수정, 로딩 UI 추가

---

src/app/main/map/[id]/page.tsx
src/components/Auth/LoginForm.tsx
src/components/Auth/PasswordCode.tsx
src/components/Auth/SignUpCode.tsx
src/components/Auth/SignUpProfile.tsx
src/components/Auth/SignUpTerms.tsx
src/components/Common/Header/Auth.tsx
src/components/Common/Header/index.tsx
src/components/Common/Menu/DropDown.tsx
src/components/Dialog/CustomModal.tsx
src/components/Map/MyMap.tsx
src/components/Mypage/MyFriendList.tsx
src/components/Mypage/MyProfile.tsx
src/components/Settings/SettingModal.tsx
src/services/mypage.ts

- 팔로워, 팔로우 목록 모달 생성
- 팔로워, 팔로우 목록 조회 가능
- 해당 목록에서 팔로잉, 언팔로우 가능

feat: 팔로워, 팔로우 리스트 구현

---

src/components/Auth/AuthCheck.ts

bug: 카카오 재발급 로직 임시 주석처리

---

src/components/Map/MyMap.tsx
src/components/Mypage/MyMap.tsx
src/components/Mypage/MyShopItem.tsx
src/types/mypage.ts

refactor: 식당 좋아요 / 좋아요 취소 오류 해결

---

jest.config.js
jest.setup.js
package-lock.json
package.json
tsconfig.json

feat: jest 테스팅 환경 설정

---

src/components/PostForm/PostContent.tsx
src/components/PostForm/PostImage.tsx
src/components/PostForm/PostSearch.tsx
src/components/PostForm/PostShopList.tsx
src/store/usePostStore.ts
src/types/post.ts

- 피드 작성 관련 컴포넌트 코드 정리 
- 변수 및 함수명 의도를 명확하게 파악할 수 있도록 수정 
- 불필요한 코드 삭제 
- 사용하지 않는 변수 및 import 삭제
- 전역 상태로 관리하는 것을 useState로 중복 관리하는 상태 삭제  
- usePostStore content 객체 코드 중복 줄이기
closed #147 
없음

[Refactor] #147 피드 작성 페이지 리팩토링

---

.github/workflows/preview.yaml

chore: Vercel 미리보기 배포를 위한 GitHub Action 설정

---

public/images/index.ts
src/components/Common/Profile/UserThumbImg.tsx
src/components/Map/KakaoMap.tsx
src/components/Map/MyListMap.tsx
src/components/Map/MyMap.tsx
src/components/Map/common.ts
src/components/SearhUser/SearhUser.tsx
tsconfig.json

- 중복 코드 제거
- src 내 경로별 alias 추가
- Marker 버그 수정
- image 파일들 index.ts 에서 관리하게끔 코드 작성.
- Common 경로에 Profile > UserThumbImg.tsx 컴포넌트 추가 ( 프로필 이미지 자주 사용되는 것 같아 생성해 뒀습니다. )
- 새로 고침 시 카카오 지도 Load 안되는 현상 발견
- Map 쪽은 거의 다 카카오 API 사용이라 간단하게 정리만 했습니다.

[Refactor] #149 맛집 지도 페이지 리팩토링

---

src/app/main/reply/[id]/page.tsx
src/components/Feed/Feed.tsx
src/components/Feed/FeedEditModal.tsx
src/components/Feed/FeedImageSlide.tsx
src/components/Feed/FeedShared.tsx
src/components/Feed/Feeds.tsx
src/components/Feed/replyList.tsx
src/services/feed.ts
src/services/reply.ts
src/styles/feedStyle.ts
src/types/feed.ts
src/types/reply.ts
tsconfig.json

- Feed 관련 컴포넌트 API 를 axios로 생성
- 함수명 컨벤션에 맞게 수정 (ex. clickBtnHandler)
- TYPE 별도 파일로 분리
- 에러 발생 시 Toast 메세지 추가
- 불필요한 코드 및 주석 삭제
- feeds 컴포넌트 API 는 axios로 생성 후 아직 연결 못 했습니다. 이 부분은 시간이 걸릴 것 같습니다!

[Refactor]: Feed 관련 컴포넌트 리팩토링

---

src/components/Settings/MySettings.tsx
src/components/Settings/SettingBadge.tsx
src/components/Settings/SettingPassword.tsx
src/components/Settings/SettingWithdrawModal.tsx

- 개인 정보 수정 관련 컴포넌트 리팩토링
- 변수 및 함수 의도 파악 쉽게 수정
- import 별칭 사용 및 사용 안하는 import 삭제 
- try catch문 정리 
closed #157 
- 로그아웃 기능은 api 에러 처리까지 수정 후 완전하게 완료할 수 있을 것 같습니다.

[Refactor] #157 개인 정보 수정 페이지 리팩토링

---

src/app/main/post/page.tsx
src/app/main/reply/[id]/page.tsx
src/components/Feed/FeedReplyList.tsx
src/components/PostForm/PostContent.tsx
src/components/PostForm/PostImage.tsx
src/components/PostForm/PostSearch.tsx
src/components/PostForm/PostShopItem.tsx
src/components/PostForm/PostShopList.tsx
src/components/Restaurant/AreaList.tsx
src/components/Restaurant/AreaOptionItem.tsx
src/components/Restaurant/AreaSelector.tsx
src/components/Restaurant/ShopFeedItem.tsx
src/components/Restaurant/ShopFeedList.tsx
src/components/Restaurant/ShopThumb.tsx
src/components/Restaurant/ShopThumbList.tsx
src/components/Settings/MySettings.tsx
src/components/Settings/SettingBadge.tsx
src/components/Settings/SettingPassword.tsx
src/components/Settings/SettingWithdrawModal.tsx
tsconfig.json

- tsconfig paths 설정 
- 담당 페이지 (피드 작성, 지역별 맛집 추천, 개인 정보 수정 페이지) import 경로 적용
closed #164 
replyList 컴포넌트명 컨벤션에 맞게 수정했습니다.

[Refactor] #164 tsconfig paths 설정 및 적용

---

tailwind.config.ts

- 색상 넘버 수정
- indigo(남색) 삭제
- gray 색상이 짙을수록 숫자가 높습니다.
- gray-0는 gray-white와 같습니다.

refactor: 색상 넘버 수정

---

src/components/PostForm/PostSearch.tsx
src/components/SearchUser/SearchInput.tsx
src/components/SearchUser/SearchUser.tsx
src/hooks/useDebounce.ts

- 유저, 식당 검색 컴포넌트에 useDebounce 커스텀 훅 적용
- 검색 Input 컴포넌트 모듈화
- 기타 수정
closed #177

Refactor: 검색 관련 컴포넌트 리팩토링 및 useDebounce 훅 생성

---

src/components/PostForm/PostImage.tsx
src/services/reply.ts
src/types/apiResponse.ts
src/types/post.ts
src/types/recommend.ts
src/types/reply.ts
src/types/restaurant.ts

- status, error 타입 포함한 ApiResponseType 분리하고 적용 
- 사용하지 않는 매개변수 삭제
closed #225

[Refactor] #225 빌드 에러나는 부분 수정

---

src/components/Common/Input/SearchInput.tsx
src/components/Mypage/MyFeedThumbnail.tsx
src/components/Mypage/MyProfileSettings.tsx
src/components/Restaurant/RestaurtandFeedsList.tsx
src/services/restaurant.ts
src/types/mypage.ts

- []  코드 업데이트
- 빌드 시 발생하는 타입 에러 수정

refactor: 타입 에러 수정

---

package-lock.json
package.json
src/components/Common/DropDown/DropDown.tsx
src/components/Common/Profile/UserThumbImg.tsx
src/components/Feed/FeedHeader.tsx
src/components/Feed/FeedReplyInput.tsx
src/components/Feed/FeedReplyItem.tsx
src/components/Feed/FeedReplyList.tsx
src/components/Feed/MentionItem.tsx
src/components/Feed/ReplyContent.tsx
src/components/SearchUser/SearchUserList.tsx
src/constants/toast.ts
src/hooks/mutations/useReplyMutation.ts
src/hooks/queries/useReplyList.ts
src/hooks/queries/useSearchUser.ts
src/services/reply.ts
src/styles/globals.css
src/types/reply.ts

- []  사소한 수정
- 댓글 기능 개선,
- 대댓글 기능 구현
- 멘션 기능 구현
closed #205 
- UserThumbImg 컴포넌트 내에서 기본 이미지 적용되도록 수정, props 수정

[Feat] #205 대댓글, 멘션 기능 구현

---

src/components/Map/MyMap.tsx
src/components/Restaurant/RestaurantCategorySlider.tsx
src/constants/tag.ts
src/services/feed.ts
src/services/restaurant.ts

- 식당 상세 페이지, 메인 피드 카테고리 페이지 필터링 로직 추가
- api 구조 변경에 따른 uri 및 props 변경

refactor: api 수정 및 식당 필터링 로직 구현

---

src/components/Feed/FeedReplyInput.tsx
src/components/Feed/FeedReplyItem.tsx
src/components/Feed/NestedReplyItem.tsx

- 대댓글에 댓글 데이터 적용했던 부분 수정
- 멘션 추가시 띄어쓰기 자동 추가
closed #244

[Feat] #244 대댓글 삭제 기능 문제 해결

---

src/components/Common/Navigation/GlobalNavigation.tsx
src/hooks/useShowPartial.ts

- 타인 마이페이지 GNB 렌더링
closed #252

[Feat] #252 타인 마이페이지 gnb 렌더링

---

src/components/Common/Dialog/DialogReport.tsx
src/components/Common/DropDown/DropDown.tsx
src/constants/settings.ts
src/constants/toast.ts
src/services/kakao.ts
src/store/useUserStore.ts
src/types/common.ts

- useUserStore 알림 플래그 수정
- 신고 관련 컴포넌트 리팩토링
- 기타 코드 리팩토링

Refactor: useUserStore 알림 플래그 수정 및 신고 관련 컴포넌트 리팩토링

---

src/components/Mypage/MyProfile.tsx

refactor: 타 회원 프로필 헤더 수정

---

src/components/Settings/PushToggle.tsx

- 푸시 알림 Mutation 적용
closed #198

feat: 푸시 알림 API 연결

---

src/components/Restaurant/ShopThumbList.tsx
src/services/restaurant.ts
src/types/restaurant.ts

- 지역 추천 맛집 데이터 없는 경우 문구 표시
- api response type 추가
closed #260

[Refactor] #260 지역별 맛집 추천 페이지 리팩토링

---

src/app/auth/kakao/callback/page.tsx
src/app/main/user/page.tsx
src/components/Auth/AuthCheck.ts
src/components/Auth/LoginForm.tsx
src/hooks/useLocalStorage.ts
src/services/kakao.ts
src/store/useUserStore.ts

- useLocalStorage 무한 재귀 호출 오류 수정
- 로그인 알림 상태 설정
- AuthCheck 카카오 로그인 토큰 재발급 추가
- 기타 코드 수정

Fix: 카카오 로그인 오류

---

src/components/Feed/FeedReplyInput.tsx
src/components/Feed/ReplyContent.tsx

- 서버에 저장되는 멘션 형태 @[닉네임](아이디) -> @닉네임 수정
closed #267

[refactor] #267 댓글 서버 저장 형태 수정

---

src/components/Feed/FeedReplyInput.tsx
src/components/Feed/ReplyContent.tsx

- 댓글에 @를 포함한 모든 문자열을 멘션으로 처리하는 문제 해결  
- includes -> startsWith 메서드로 수정 
close #272

[Fix] #272 멘션 필터링 메서드 수정

---

src/app/auth/kakao/callback/page.tsx
src/components/Auth/ChangePassword.tsx
src/components/Auth/KaKaoTerms.tsx
src/components/Auth/SignUpProfile.tsx
src/components/Settings/WithdrawModal.tsx

- 토스트 표시 후 페이지 이동되도록 setTimeout 추가

refactor: 토스트 표시 후 페이지 이동 지연

---

src/app/auth/kakao/callback/page.tsx
src/components/Auth/ChangePassword.tsx
src/components/Auth/KaKaoTerms.tsx
src/components/Auth/SignUpProfile.tsx
src/components/Feed/Feeds.tsx
src/components/Settings/WithdrawModal.tsx

- setTimeout delay 수정
- 스크롤 유지 로직 삭제

refactor: setTimeout delay 수정 및 스크롤 유지 로직 삭제

---

src/app/auth/kakao/callback/page.tsx
src/components/Auth/AuthCheck.ts
src/hooks/useLogout.ts

- AuthCheck 카카오 로그인 토큰 재발급 수정
- 로그아웃 clearUser 위치 수정

Refactor: 카카오 로그인 토큰 재발급 및 로그아웃 수정

---

src/components/Auth/AuthCheck.ts

- 에러 발생시 로그인 페이지로 라우팅
- clearUser매서드 적용 안 되는 부분 localStorage.removeItem 적용

Refactor: AuthCheck 로직 수정

---

src/app/auth/kakao/callback/page.tsx
src/components/Auth/AuthCheck.ts

refactor: 카카오로그인 에러시 카카오로그아웃

---

src/app/main/recommend/page.tsx
src/app/main/recommend/reviews/[id]/page.tsx
src/app/main/settings/layout.tsx
src/components/Common/Input/SearchInput.tsx
src/components/PostForm/PostSearch.tsx
src/components/SearchUser/SearchUser.tsx
src/components/Settings/MySettings.tsx
src/components/Settings/SettingBadge.tsx
src/components/Settings/SettingPassword.tsx

- 피드 작성 페이지 맛집 검색 부분 문구 수정
- 개인 정보 수정, 지역별 맛집 추천 페이지 max width, margin 설정
closed #289

[Refactor] #289 디자인 수정

---

src/components/Auth/AuthCheck.ts
src/components/Auth/SignUpForm.tsx
src/components/Common/Button/FollowButton.tsx
src/components/Feed/FeedUserCard.tsx
src/services/kakao.ts

- AuthCheck에서 새로고침 시 로그아웃되는 에러 수정
- Kakao 토큰 발급 API URL 중복 삭제
- <P> 태그 중첩 에러 해결
- import 이름 중복 수정

fix: 새로고침 시 로그아웃되는 에러 및 <P> 태그 중첩 에러 해결

---

public/firebase-messaging-sw.js
src/components/Auth/LoginForm.tsx

- firebase-messaging-sw.js 에서 import 오류 발생하여 이전 로직으로 수정
- 로그인 에러 관련 토스트 오류로 인해 alert로 변경
- firebase-messaging-sw.js 에서 import 오류

Refactor: firebase import 오류 및 로그인 toast 오류 수정

---

public/.well-known/assetlinks.json

chore: 디지털 애셋 링크 JSON 파일 추가
